### ISSUE TITLE
service 这种写法，url带参数如何实现

### ISSUE THREAD

**Issue by TerryChenUI** [cklwblove/vue-element-admin-ts#4]
例如 api/company/{companyId}/user/{userId}

**Comment by cklwblove** [comment]
你有什么好的思路吗，欢迎提交 pr

**Comment by cklwblove** [comment]
> 例如 api/company/{companyId}/user/{userId}

可以参考 https://github.com/cklwblove/vue-preset/blob/ece3b851d947ec00d42815919ca32bb1e84be1b3/generator/template/src/services/request.js#L136
